export type Lang = 'en' | 'hu'

export const T = {
  en: {
    // Header
    usageIntelligence: 'Usage Intelligence',
    subtitle: 'Anthropic Claude Max',
    jarvisTitle: '⬡ JARVIS STATS',
    claudeTitle: 'Claude Stats',
    refresh: '↻ Refresh',
    refreshing: '↻ Syncing…',
    refreshed: '✓ Updated',
    loading: 'Loading…',

    // Nav
    jarvis: 'Jarvis',
    claude: 'Claude',

    // Period labels (full)
    today: 'Today',
    daily: '7 days',
    weekly: '4 weeks',
    monthly: '6 months',
    allTime: 'All time',
    custom: 'Custom',

    // Period labels (jarvis abbreviated CAPS)
    todayCaps: 'TODAY',
    dailyCaps: '7D',
    weeklyCaps: '4W',
    monthlyCaps: '6M',
    allTimeCaps: 'ALL',
    customCaps: 'CUSTOM',

    // Date range
    dateArrow: '→',

    // Metric cards
    totalCost: 'Total Cost',
    activeHours: 'Active Hours',
    sessions: 'Sessions',
    totalTokens: 'Total Tokens',
    thisPeriod: 'this period',
    span: 'span',
    projects: 'projects',
    cacheRead: 'cache read',

    // Section headers
    costOverTime: 'Cost over time',
    tokenBreakdown: 'Token breakdown',
    activeHoursChart: 'Active hours',
    sessionsChart: 'Sessions',
    activity: 'Activity',
    workingHours: 'Working hours',
    projectsSection: 'Projects',
    modelsSection: 'Models',
    usageSection: 'Usage',

    // Subtitles
    usdPeriod: 'USD / period',
    stacked: 'stacked',
    perDay: 'per day',
    weeksIntensity: '52 weeks · cost intensity',
    activeSpanIdle: 'active · span · idle',
    tokenDist: 'token distribution',
    vsPeak: 'vs peak',

    // Project table
    colProject: 'Project',
    colCost: 'Cost',
    colHours: 'Hours',
    colSessions: 'Sessions',
    colShare: 'Share',
    showMore: (n: number) => `▼ SHOW ${n} MORE`,
    showLess: '▲ SHOW LESS',

    // Hours display
    active: 'Active',
    spanLabel: 'Span',
    idle: 'Idle',

    // Usage limits
    sessionLabel: 'Current session (last 5h)',
    sessionSub: 'vs your peak day',
    weekAllLabel: 'This week — all models',
    weekSonnetLabel: 'This week — Sonnet only',
    resets: 'Resets',
    usageFooter: '% = this period vs your all-time peak week',
    ofPeak: '% of peak',

    // Activity heatmap
    favoriteModel: 'Favorite model',
    totalTokensStat: 'Total tokens',
    activeDays: 'Active days',
    longestStreak: 'Longest streak',
    days: 'days',

    // Models
    ioLabel: 'I/O',
    inLabel: 'In',
    outLabel: 'Out',

    // Hours display extra
    efficiency: 'Efficiency',

    // Heatmap legend
    less: 'Less',
    more: 'More',
    currentStreak: 'Current streak',
    sessionsLabel: 'Sessions',
    dowLabels: ['Mon', '', 'Wed', '', 'Fri', '', ''] as string[],

    // Jarvis-specific
    from: 'FROM',
    to: 'TO',
    range: 'RANGE',
    lastSync: 'LAST SYNC',
    sysOnline: 'SYS: ONLINE',
    daysSelected: (n: number) => `${n} day${n !== 1 ? 's' : ''} selected`,
    tokensPerDay: 'tokens per day',
    weeklyLimits: '/usage — Weekly Limits',
    activityOverview: 'Activity Overview',
    projectMatrix: 'Project Matrix',
    costTimeline: 'Cost Timeline',
    tokenBreakdownLabel: 'Token Breakdown',

    // Footer
    footer: 'Generated by claude-stats · Updated daily at 06:00',
    total: 'total',
  },

  hu: {
    // Header
    usageIntelligence: 'Felhasználás elemzése',
    subtitle: 'Anthropic Claude Max',
    jarvisTitle: '⬡ JARVIS STATISZTIKA',
    claudeTitle: 'Claude Statisztika',
    refresh: '↻ Frissítés',
    refreshing: '↻ Szinkronizálás…',
    refreshed: '✓ Kész',
    loading: 'Betöltés…',

    // Nav
    jarvis: 'Jarvis',
    claude: 'Claude',

    // Period labels (full)
    today: 'Ma',
    daily: '7 nap',
    weekly: '4 hét',
    monthly: '6 hónap',
    allTime: 'Összes',
    custom: 'Egyéni',

    // Period labels (jarvis abbreviated CAPS)
    todayCaps: 'MA',
    dailyCaps: '7N',
    weeklyCaps: '4H',
    monthlyCaps: '6HÓ',
    allTimeCaps: 'ÖSSZES',
    customCaps: 'EGYÉNI',

    // Date range
    dateArrow: '→',

    // Metric cards
    totalCost: 'Összes költség',
    activeHours: 'Aktív órák',
    sessions: 'Munkamenetek',
    totalTokens: 'Összes token',
    thisPeriod: 'ebben az időszakban',
    span: 'teljes',
    projects: 'projekt',
    cacheRead: 'cache-olvasás',

    // Section headers
    costOverTime: 'Költség időben',
    tokenBreakdown: 'Token megoszlás',
    activeHoursChart: 'Aktív órák',
    sessionsChart: 'Munkamenetek',
    activity: 'Aktivitás',
    workingHours: 'Munkaidő',
    projectsSection: 'Projektek',
    modelsSection: 'Modellek',
    usageSection: 'Felhasználás',

    // Subtitles
    usdPeriod: 'USD / időszak',
    stacked: 'halmozott',
    perDay: 'naponta',
    weeksIntensity: '52 hét · költségintenzitás',
    activeSpanIdle: 'aktív · teljes · tétlen',
    tokenDist: 'token megoszlás',
    vsPeak: 'csúcshoz képest',

    // Project table
    colProject: 'Projekt',
    colCost: 'Költség',
    colHours: 'Órák',
    colSessions: 'Munkam.',
    colShare: 'Arány',
    showMore: (n: number) => `▼ MUTASS ${n}-T TÖBBET`,
    showLess: '▲ MUTASS KEVESEBBET',

    // Hours display
    active: 'Aktív',
    spanLabel: 'Teljes',
    idle: 'Tétlen',

    // Usage limits
    sessionLabel: 'Jelenlegi munkamenet (utolsó 5 óra)',
    sessionSub: 'csúcsnaphoz képest',
    weekAllLabel: 'Ez a hét — összes modell',
    weekSonnetLabel: 'Ez a hét — csak Sonnet',
    resets: 'Újraindul',
    usageFooter: '% = ez az időszak az összes idők csúcshete alapján',
    ofPeak: '% a csúcshoz képest',

    // Activity heatmap
    favoriteModel: 'Kedvenc modell',
    totalTokensStat: 'Összes token',
    activeDays: 'Aktív napok',
    longestStreak: 'Leghosszabb sorozat',
    days: 'nap',

    // Models
    ioLabel: 'Be/Ki',
    inLabel: 'Be',
    outLabel: 'Ki',

    // Hours display extra
    efficiency: 'Hatékonyság',

    // Heatmap legend
    less: 'Kevés',
    more: 'Több',
    currentStreak: 'Jelenlegi sorozat',
    sessionsLabel: 'Munkamenetek',
    dowLabels: ['H', '', 'Sze', '', 'P', '', ''] as string[],

    // Jarvis-specific
    from: 'TÓL',
    to: 'IG',
    range: 'IDŐSZAK',
    lastSync: 'SZINKRON',
    sysOnline: 'RENDSZER: AKTÍV',
    daysSelected: (n: number) => `${n} nap kijelölve`,
    tokensPerDay: 'token naponta',
    weeklyLimits: 'Heti felhasználás',
    activityOverview: 'Aktivitás áttekintés',
    projectMatrix: 'Projekt mátrix',
    costTimeline: 'Költség idősor',
    tokenBreakdownLabel: 'Token megoszlás',

    // Footer
    footer: 'Claude-stats generálta · Naponta frissítve 06:00-kor',
    total: 'összesen',
  },
} as const
